project_id = "vodglzbgqsafghlihivy"

[functions.ai-chat]
verify_jwt = true

[functions.analyze-asphalt]
verify_jwt = true

[functions.get-mapbox-token]
verify_jwt = true

[functions.maps]
verify_jwt = true

[functions.game-get-profile]
verify_jwt = true

[functions.game-get-leaderboard]
verify_jwt = true

[functions.game-process-event]
verify_jwt = true
