import { gradients } from "./tokens";
import { ThemeDefinition, ThemeId } from "./types";

const tacticalDarkVars: Record<string, string> = {
  "--primary": "30 100% 50%",
  "--accent": "197 100% 50%",
  "--background": "0 0% 4%",
  "--foreground": "0 0% 88%",
  "--card": "0 0% 6%",
  "--card-foreground": "0 0% 88%",
  "--popover": "0 0% 6%",
  "--popover-foreground": "0 0% 88%",
  "--muted": "0 0% 10%",
  "--muted-foreground": "0 0% 60%",
  "--primary-foreground": "0 0% 100%",
  "--accent-foreground": "0 0% 100%",
  "--destructive": "0 100% 54%",
  "--destructive-foreground": "0 0% 100%",
  "--success": "130 100% 50%",
  "--success-foreground": "0 0% 10%",
  "--border": "0 0% 15%",
  "--input": "0 0% 12%",
  "--ring": "30 100% 50%",
};

const themeDefinitions: ThemeDefinition[] = [
  {
    id: "tactical-dark",
    name: "Tactical Dark",
    shortName: "Tactical",
    description: "Command center baseline palette inspired by tactical HUDs.",
    category: "core",
    cssVars: tacticalDarkVars,
    wallpaper: "mission-grid",
    accentGradient: gradients.command,
    accessibility: {
      highContrast: false,
      colorBlindSafe: true,
    },
    tags: ["default", "mission"],
  },
  {
    id: "light",
    name: "Luminous",
    description: "Bright neutral palette for daylight planning and invoices.",
    category: "core",
    cssVars: {
      "--background": "0 0% 98%",
      "--foreground": "0 0% 10%",
      "--card": "0 0% 100%",
      "--card-foreground": "0 0% 10%",
      "--primary": "220 90% 56%",
      "--primary-foreground": "0 0% 100%",
      "--accent": "260 90% 56%",
      "--muted": "0 0% 92%",
      "--muted-foreground": "0 0% 35%",
      "--border": "0 0% 80%",
      "--input": "0 0% 90%",
      "--ring": "220 90% 56%",
    },
    wallpaper: "legacy",
    accentGradient: gradients.sanctuary,
    accessibility: {
      highContrast: true,
      colorBlindSafe: true,
    },
    tags: ["day", "finance"],
  },
  {
    id: "high-contrast",
    name: "High Contrast",
    description: "Black and gold scheme tuned for maximum contrast.",
    category: "accessibility",
    cssVars: {
      "--background": "0 0% 0%",
      "--foreground": "0 0% 100%",
      "--card": "0 0% 0%",
      "--card-foreground": "0 0% 100%",
      "--primary": "40 100% 50%",
      "--primary-foreground": "0 0% 0%",
      "--accent": "200 100% 50%",
      "--muted": "0 0% 12%",
      "--muted-foreground": "0 0% 92%",
      "--border": "0 0% 25%",
      "--input": "0 0% 20%",
      "--ring": "40 100% 50%",
    },
    wallpaper: "ember-gold",
    accentGradient: gradients.alert,
    accessibility: {
      highContrast: true,
      colorBlindSafe: true,
    },
    tags: ["a11y"],
  },
  {
    id: "color-blind",
    name: "Blue/Orange A11y",
    description: "Deuteranopia-friendly palette with vivid contrast.",
    category: "accessibility",
    cssVars: {
      "--background": "0 0% 6%",
      "--foreground": "0 0% 96%",
      "--card": "0 0% 8%",
      "--card-foreground": "0 0% 96%",
      "--primary": "205 100% 55%",
      "--primary-foreground": "0 0% 100%",
      "--accent": "30 100% 55%",
      "--accent-foreground": "0 0% 10%",
      "--muted": "0 0% 12%",
      "--muted-foreground": "0 0% 78%",
      "--border": "0 0% 18%",
      "--input": "0 0% 14%",
      "--ring": "205 100% 55%",
    },
    wallpaper: "uplift",
    accessibility: {
      highContrast: true,
      colorBlindSafe: true,
      recommendedFor: ["Deuteranopia", "Protanopia"],
    },
    tags: ["a11y", "field"],
  },
  {
    id: "colorblind-safe",
    name: "Colorblind Safe (Variant)",
    description: "Alternate blue/orange palette with slightly softer accents.",
    category: "accessibility",
    cssVars: {
      "--background": "0 0% 6%",
      "--foreground": "0 0% 96%",
      "--card": "0 0% 8%",
      "--card-foreground": "0 0% 96%",
      "--primary": "205 100% 55%",
      "--primary-foreground": "0 0% 100%",
      "--accent": "30 100% 55%",
      "--accent-foreground": "0 0% 10%",
      "--muted": "0 0% 12%",
      "--muted-foreground": "0 0% 78%",
      "--border": "0 0% 18%",
      "--input": "0 0% 14%",
      "--ring": "205 100% 55%",
    },
    wallpaper: "uplift",
    accessibility: {
      highContrast: true,
      colorBlindSafe: true,
    },
    tags: ["a11y"],
  },
  {
    id: "industry-blue",
    name: "Industry Blue",
    description: "Corporate blue with amber accents for executive briefings.",
    category: "industry",
    cssVars: {
      "--primary": "211 100% 45%",
      "--primary-foreground": "0 0% 100%",
      "--accent": "39 100% 50%",
      "--background": "220 19% 10%",
      "--foreground": "0 0% 96%",
    },
    wallpaper: "nav-blueprint",
    accentGradient: gradients.focus,
    tags: ["executive", "reporting"],
  },
  {
    id: "safety-green",
    name: "Safety Green",
    description: "High-visibility scheme for field crew ops dashboards.",
    category: "industry",
    cssVars: {
      "--primary": "130 100% 45%",
      "--primary-foreground": "0 0% 10%",
      "--accent": "30 100% 50%",
      "--background": "140 10% 6%",
      "--foreground": "0 0% 92%",
    },
    wallpaper: "uplift",
    tags: ["field", "crew"],
  },
  {
    id: "construction",
    name: "Construction Gold",
    description: "Amber and cobalt palette for bid review war rooms.",
    category: "premium",
    premium: true,
    cssVars: {
      "--primary": "28 95% 52%",
      "--primary-foreground": "0 0% 10%",
      "--accent": "210 80% 52%",
      "--background": "215 22% 9%",
      "--foreground": "0 0% 96%",
    },
    wallpaper: "ember-gold",
    tags: ["premium", "estimating"],
  },
  {
    id: "landscaping",
    name: "Landscaping Evergreen",
    description: "Verdant palette for green ministry and campus planning dashboards.",
    category: "premium",
    premium: true,
    cssVars: {
      "--primary": "133 70% 41%",
      "--primary-foreground": "0 0% 98%",
      "--accent": "43 93% 55%",
      "--background": "100 15% 8%",
      "--foreground": "0 0% 95%",
    },
    wallpaper: "revival",
    tags: ["premium", "grounds"],
  },
  {
    id: "security",
    name: "Security Watch",
    description: "Deep navy with white accents for compliance monitoring.",
    category: "premium",
    premium: true,
    cssVars: {
      "--primary": "220 90% 56%",
      "--primary-foreground": "0 0% 100%",
      "--accent": "0 0% 100%",
      "--background": "220 15% 6%",
      "--foreground": "0 0% 92%",
    },
    wallpaper: "steelworks",
    tags: ["premium", "security"],
  },
  {
    id: "aviation",
    name: "Aviation Beacon",
    description: "Azure and violet accents for runway and airside scheduling.",
    category: "premium",
    premium: true,
    cssVars: {
      "--primary": "197 100% 50%",
      "--primary-foreground": "0 0% 10%",
      "--accent": "258 90% 64%",
      "--background": "240 13% 10%",
      "--foreground": "0 0% 94%",
    },
    wallpaper: "night-ops-grid",
    tags: ["premium", "aviation"],
  },
  {
    id: "division-shd",
    name: "Division SHD",
    description: "Inspired orange/cyan HUD for mission briefings.",
    category: "faithful",
    cssVars: {
      "--primary": "30 100% 50%",
      "--primary-foreground": "0 0% 100%",
      "--accent": "197 100% 55%",
      "--accent-foreground": "0 0% 100%",
      "--background": "0 0% 3%",
      "--foreground": "0 0% 92%",
      "--card": "0 0% 6%",
      "--card-foreground": "0 0% 92%",
      "--muted": "0 0% 12%",
      "--muted-foreground": "0 0% 70%",
      "--border": "0 0% 14%",
      "--input": "0 0% 12%",
      "--ring": "30 100% 50%",
    },
    wallpaper: "mission-grid",
    accentGradient: gradients.command,
    tags: ["hud", "faithful"],
  },
  {
    id: "division-shd-faithful",
    name: "Division SHD (Faithful)",
    description: "High-fidelity orange/cyan with deeper blacks.",
    category: "faithful",
    cssVars: {
      "--primary": "30 100% 54%",
      "--primary-foreground": "0 0% 100%",
      "--accent": "197 100% 58%",
      "--accent-foreground": "0 0% 100%",
      "--background": "0 0% 2%",
      "--foreground": "0 0% 95%",
      "--card": "0 0% 5%",
      "--card-foreground": "0 0% 95%",
      "--muted": "0 0% 10%",
      "--muted-foreground": "0 0% 72%",
      "--border": "0 0% 16%",
      "--input": "0 0% 12%",
      "--ring": "30 100% 54%",
    },
    wallpaper: "mission-grid",
  },
  {
    id: "dark-zone",
    name: "Dark Zone",
    description: "Deep noir base with hazard beacons for risk dashboards.",
    category: "faithful",
    cssVars: {
      "--primary": "0 85% 55%",
      "--primary-foreground": "0 0% 100%",
      "--accent": "186 85% 45%",
      "--accent-foreground": "0 0% 100%",
      "--background": "0 0% 2%",
      "--foreground": "0 0% 95%",
      "--card": "0 0% 6%",
      "--card-foreground": "0 0% 95%",
      "--muted": "0 0% 12%",
      "--muted-foreground": "0 0% 70%",
      "--border": "0 0% 14%",
      "--input": "0 0% 12%",
      "--ring": "0 85% 55%",
    },
    wallpaper: "stormsetter",
  },
  {
    id: "dark-zone-faithful",
    name: "Dark Zone (Faithful)",
    description: "Enhanced warning reds and cooler cyan tracers.",
    category: "faithful",
    cssVars: {
      "--primary": "0 90% 56%",
      "--primary-foreground": "0 0% 100%",
      "--accent": "186 90% 48%",
      "--accent-foreground": "0 0% 100%",
      "--background": "0 0% 1.5%",
      "--foreground": "0 0% 96%",
      "--card": "0 0% 5%",
      "--card-foreground": "0 0% 96%",
      "--muted": "0 0% 10%",
      "--muted-foreground": "0 0% 72%",
      "--border": "0 0% 16%",
      "--input": "0 0% 12%",
      "--ring": "0 90% 56%",
    },
    wallpaper: "stormsetter",
  },
  {
    id: "black-tusk",
    name: "Black Tusk",
    description: "Emerald and steel palette for advanced analytics ops.",
    category: "faithful",
    cssVars: {
      "--primary": "135 95% 50%",
      "--primary-foreground": "0 0% 10%",
      "--accent": "220 15% 75%",
      "--accent-foreground": "0 0% 10%",
      "--background": "220 9% 6%",
      "--foreground": "0 0% 95%",
      "--card": "220 9% 8%",
      "--card-foreground": "0 0% 95%",
      "--muted": "220 8% 14%",
      "--muted-foreground": "0 0% 75%",
      "--border": "220 8% 16%",
      "--input": "220 8% 14%",
      "--ring": "135 95% 50%",
    },
    wallpaper: "steelworks",
  },
  {
    id: "black-tusk-faithful",
    name: "Black Tusk (Faithful)",
    description: "Sharper neons and deeper shadows for intel missions.",
    category: "faithful",
    cssVars: {
      "--primary": "135 98% 52%",
      "--primary-foreground": "0 0% 10%",
      "--accent": "220 18% 76%",
      "--accent-foreground": "0 0% 10%",
      "--background": "220 10% 5%",
      "--foreground": "0 0% 96%",
      "--card": "220 10% 7%",
      "--card-foreground": "0 0% 96%",
      "--muted": "220 9% 13%",
      "--muted-foreground": "0 0% 76%",
      "--border": "220 9% 18%",
      "--input": "220 9% 14%",
      "--ring": "135 98% 52%",
    },
    wallpaper: "steelworks",
  },
  {
    id: "isac-core",
    name: "ISAC Core",
    description: "Orange/teal mix with balanced neutrals for AI consoles.",
    category: "faithful",
    cssVars: {
      "--primary": "30 100% 50%",
      "--primary-foreground": "0 0% 100%",
      "--accent": "196 100% 50%",
      "--accent-foreground": "0 0% 100%",
      "--background": "0 0% 2%",
      "--foreground": "0 0% 94%",
      "--card": "0 0% 6%",
      "--card-foreground": "0 0% 94%",
      "--muted": "0 0% 11%",
      "--muted-foreground": "0 0% 70%",
      "--border": "0 0% 15%",
      "--input": "0 0% 12%",
      "--ring": "30 100% 50%",
    },
    wallpaper: "mission-grid",
  },
  {
    id: "hunter",
    name: "Hunter Protocol",
    description: "Amber and white strike palette for elite response drills.",
    category: "limited",
    cssVars: {
      "--primary": "24 88% 52%",
      "--primary-foreground": "0 0% 100%",
      "--accent": "0 0% 100%",
      "--accent-foreground": "0 0% 10%",
      "--background": "0 0% 2%",
      "--foreground": "0 0% 94%",
      "--card": "0 0% 6%",
      "--card-foreground": "0 0% 94%",
      "--muted": "0 0% 12%",
      "--muted-foreground": "0 0% 70%",
      "--border": "0 0% 16%",
      "--input": "0 0% 12%",
      "--ring": "24 88% 52%",
    },
    wallpaper: "ember-gold",
  },
  {
    id: "rogue-agent",
    name: "Rogue Agent",
    description: "Aggressive red/orange for incident escalation boards.",
    category: "limited",
    cssVars: {
      "--primary": "0 86% 54%",
      "--primary-foreground": "0 0% 100%",
      "--accent": "30 100% 50%",
      "--accent-foreground": "0 0% 100%",
      "--background": "0 0% 2%",
      "--foreground": "0 0% 95%",
      "--card": "0 0% 6%",
      "--card-foreground": "0 0% 95%",
      "--muted": "0 0% 12%",
      "--muted-foreground": "0 0% 72%",
      "--border": "0 0% 16%",
      "--input": "0 0% 12%",
      "--ring": "0 86% 54%",
    },
    wallpaper: "ember-gold",
  },
  {
    id: "contaminated",
    name: "Contaminated Zone",
    description: "Hazard yellow-green paired with alert red for weather locks.",
    category: "limited",
    cssVars: {
      "--primary": "80 100% 45%",
      "--primary-foreground": "0 0% 10%",
      "--accent": "0 85% 54%",
      "--accent-foreground": "0 0% 100%",
      "--background": "0 0% 3%",
      "--foreground": "0 0% 94%",
      "--card": "0 0% 6%",
      "--card-foreground": "0 0% 94%",
      "--muted": "0 0% 12%",
      "--muted-foreground": "0 0% 72%",
      "--border": "0 0% 14%",
      "--input": "0 0% 12%",
      "--ring": "80 100% 45%",
    },
    wallpaper: "stormsetter",
  },
  {
    id: "night-ops",
    name: "Night Ops",
    description: "Blue neon for overnight sealcoating missions and crew rotations.",
    category: "limited",
    cssVars: {
      "--primary": "210 90% 60%",
      "--primary-foreground": "0 0% 100%",
      "--accent": "197 100% 50%",
      "--accent-foreground": "0 0% 100%",
      "--background": "0 0% 2%",
      "--foreground": "0 0% 95%",
      "--card": "0 0% 6%",
      "--card-foreground": "0 0% 95%",
      "--muted": "0 0% 12%",
      "--muted-foreground": "0 0% 70%",
      "--border": "0 0% 15%",
      "--input": "0 0% 12%",
      "--ring": "210 90% 60%",
    },
    wallpaper: "night-ops-grid",
  },
];

export const THEME_DEFINITIONS = themeDefinitions;

export const themeRegistry = new Map<ThemeId, ThemeDefinition>(
  themeDefinitions.map((definition) => [definition.id, definition]),
);

export const defaultThemeId: ThemeId = "tactical-dark";

export function getThemeDefinition(id: ThemeId): ThemeDefinition {
  return themeRegistry.get(id) ?? themeRegistry.get(defaultThemeId)!;
}

export function listThemeDefinitions(): ThemeDefinition[] {
  return THEME_DEFINITIONS;
}
