import { gradients } from "../tokens";
import { ThemeConfig } from "./types";

export const faithfulThemes: ThemeConfig[] = [
  {
    id: "division-shd",
    name: "Division Agent",
    shortName: "Agent",
    description: "Faithful SHD orange with cyan tracers for mission briefings.",
    category: "faithful",
    mode: "dark",
    css: {
      "--primary": "31 100% 56%",
      "--primary-foreground": "0 0% 100%",
      "--accent": "196 100% 58%",
      "--accent-foreground": "0 0% 12%",
      "--background": "210 42% 5%",
      "--foreground": "210 25% 94%",
      "--card": "210 38% 7%",
      "--card-foreground": "210 25% 94%",
      "--border": "214 34% 16%",
      "--muted": "214 28% 14%",
      "--muted-foreground": "210 20% 70%",
      "--hud-grid-color": "rgba(255,111,15,0.18)",
      "--hud-grid-color-soft": "rgba(109,200,255,0.12)",
      "--primary-glow": "31 100% 62%",
    },
    wallpaper: "division-agent",
    accentGradient: gradients.command,
    badges: ["Lore"],
    tags: ["division", "hud"],
    hud: {
      gridColor: "rgba(255,111,15,0.18)",
      cornerAccent: "rgba(196,196,196,0.42)",
      glow: "rgba(109,200,255,0.32)",
    },
  },
  {
    id: "division-shd-faithful",
    name: "Division Agent (Faithful)",
    description: "High-fidelity SHD palette with deeper shadows for cinematic dashboards.",
    category: "faithful",
    mode: "dark",
    css: {
      "--background": "220 52% 3%",
      "--foreground": "0 0% 96%",
      "--card": "220 50% 5%",
      "--card-foreground": "0 0% 96%",
      "--primary": "30 100% 58%",
      "--accent": "197 100% 60%",
      "--border": "220 42% 14%",
      "--hud-grid-color": "rgba(255,111,15,0.2)",
      "--hud-grid-color-soft": "rgba(108,211,255,0.14)",
      "--primary-glow": "30 100% 64%",
    },
    wallpaper: "division-agent",
    accentGradient: gradients.command,
    tags: ["division", "immersive"],
  },
  {
    id: "dark-zone",
    name: "Dark Zone",
    description: "Deep noir base with hazard beacons for threat monitoring.",
    category: "faithful",
    mode: "dark",
    css: {
      "--primary": "0 86% 58%",
      "--primary-foreground": "0 0% 100%",
      "--accent": "186 85% 46%",
      "--accent-foreground": "0 0% 12%",
      "--background": "220 38% 3%",
      "--foreground": "0 0% 96%",
      "--hud-grid-color": "rgba(230,57,70,0.28)",
      "--hud-grid-color-soft": "rgba(108,211,255,0.12)",
    },
    wallpaper: "dark-zone",
    accentGradient: gradients.alert,
    tags: ["threat", "intel"],
    hud: {
      gridColor: "rgba(230,57,70,0.28)",
      cornerAccent: "rgba(230,57,70,0.65)",
      glow: "rgba(108,211,255,0.26)",
    },
  },
  {
    id: "dark-zone-faithful",
    name: "Dark Zone (Faithful)",
    description: "Amplified crimson beacons with cooler cyan tracers.",
    category: "faithful",
    mode: "dark",
    css: {
      "--background": "225 48% 2%",
      "--foreground": "0 0% 97%",
      "--card": "225 40% 4%",
      "--card-foreground": "0 0% 97%",
      "--primary": "0 92% 60%",
      "--accent": "188 90% 50%",
      "--border": "225 34% 12%",
      "--hud-grid-color": "rgba(230,57,70,0.34)",
      "--primary-glow": "0 92% 66%",
    },
    wallpaper: "dark-zone-threat",
    accentGradient: gradients.alert,
    tags: ["threat", "lore"],
  },
  {
    id: "isac-core",
    name: "Tech Specialist",
    description: "Cyan diagnostics palette optimised for AI-assisted analytics.",
    category: "faithful",
    mode: "dark",
    css: {
      "--primary": "196 100% 58%",
      "--primary-foreground": "0 0% 10%",
      "--accent": "30 100% 54%",
      "--accent-foreground": "0 0% 6%",
      "--background": "220 46% 6%",
      "--hud-grid-color": "rgba(108,211,255,0.22)",
      "--primary-glow": "196 100% 64%",
    },
    wallpaper: "tech-specialist",
    accentGradient: gradients.data,
    tags: ["ai", "analytics"],
    hud: {
      gridColor: "rgba(108,211,255,0.22)",
      cornerAccent: "rgba(108,211,255,0.42)",
      glow: "rgba(108,211,255,0.38)",
    },
  },
  {
    id: "black-tusk",
    name: "Black Tusk",
    description: "Emerald and steel palette for advanced analytics ops.",
    category: "faithful",
    mode: "dark",
    css: {
      "--primary": "135 95% 50%",
      "--primary-foreground": "0 0% 10%",
      "--accent": "220 15% 75%",
      "--accent-foreground": "0 0% 10%",
      "--background": "220 12% 7%",
    },
    wallpaper: "steelworks",
    accentGradient: gradients.stealth,
    tags: ["analytics", "intel"],
  },
  {
    id: "black-tusk-faithful",
    name: "Black Tusk (Faithful)",
    description: "Sharper neons and deeper shadows for intel missions.",
    category: "faithful",
    mode: "dark",
    css: {
      "--background": "220 18% 5%",
      "--foreground": "0 0% 96%",
      "--card": "220 16% 7%",
      "--card-foreground": "0 0% 96%",
      "--primary": "135 98% 52%",
      "--primary-foreground": "0 0% 10%",
      "--accent": "220 18% 76%",
      "--accent-foreground": "0 0% 10%",
      "--border": "220 16% 12%",
    },
    wallpaper: "steelworks",
    accentGradient: gradients.stealth,
    tags: ["analytics", "immersive"],
  },
];
