import { gradients } from "../tokens";
import { ThemeConfig } from "./types";

export const limitedThemes: ThemeConfig[] = [
  {
    id: "rogue-agent",
    name: "Rogue Agent",
    description: "Aggressive crimson and amber for incident escalation boards.",
    category: "limited",
    mode: "dark",
    css: {
      "--primary": "0 86% 58%",
      "--primary-foreground": "0 0% 100%",
      "--accent": "31 100% 54%",
      "--accent-foreground": "0 0% 100%",
      "--hud-grid-color": "rgba(230,57,70,0.32)",
      "--hud-grid-color-soft": "rgba(255,150,70,0.24)",
    },
    wallpaper: "rogue-agent-grid",
    accentGradient: gradients.alert,
    badges: ["Incident"],
    tags: ["alert", "response"],
    hud: {
      gridColor: "rgba(230,57,70,0.32)",
      cornerAccent: "rgba(255,150,70,0.55)",
      glow: "rgba(230,57,70,0.4)",
    },
  },
  {
    id: "hunter",
    name: "Hunter Protocol",
    description: "Amber and white strike palette for elite response drills.",
    category: "limited",
    mode: "dark",
    css: {
      "--primary": "28 94% 58%",
      "--primary-foreground": "0 0% 8%",
      "--accent": "0 0% 100%",
      "--accent-foreground": "0 0% 10%",
      "--hud-grid-color": "rgba(255,195,150,0.2)",
      "--primary-glow": "28 94% 64%",
    },
    wallpaper: "hunter-protocol-grid",
    accentGradient: gradients.focus,
    badges: ["Elite"],
    tags: ["response", "elite"],
  },
  {
    id: "night-ops",
    name: "Stealth Operations",
    description: "Blue neon for overnight sealcoating missions and crew rotations.",
    category: "limited",
    mode: "dark",
    css: {
      "--primary": "210 90% 60%",
      "--primary-foreground": "0 0% 100%",
      "--accent": "197 100% 52%",
      "--accent-foreground": "0 0% 100%",
      "--hud-grid-color": "rgba(108,211,255,0.24)",
    },
    wallpaper: "stealth-operations-grid",
    accentGradient: gradients.data,
    tags: ["crew", "night"],
  },
  {
    id: "contaminated",
    name: "Hazard Control",
    description: "Hazard yellow-green paired with alert red for weather locks.",
    category: "limited",
    mode: "dark",
    css: {
      "--primary": "82 92% 48%",
      "--primary-foreground": "0 0% 10%",
      "--accent": "0 85% 54%",
      "--accent-foreground": "0 0% 100%",
      "--hud-grid-color": "rgba(250,204,21,0.26)",
    },
    wallpaper: "dark-zone-threat",
    badges: ["Incident"],
    tags: ["weather", "alert"],
  },
];
