import { gradients } from "../tokens";
import { ThemeConfig } from "./types";

export const premiumThemes: ThemeConfig[] = [
  {
    id: "construction",
    name: "Combat Mode",
    description: "Amber and cobalt palette for go/no-go bid reviews.",
    category: "premium",
    mode: "dark",
    premium: true,
    css: {
      "--primary": "28 95% 52%",
      "--primary-foreground": "0 0% 10%",
      "--accent": "210 80% 52%",
      "--accent-foreground": "0 0% 98%",
      "--background": "220 24% 8%",
    },
    wallpaper: "ember-gold",
    accentGradient: gradients.focus,
    badges: ["Premium"],
    tags: ["sales", "review"],
  },
  {
    id: "security",
    name: "Security Watch",
    description: "Deep navy with white accents for compliance monitoring.",
    category: "premium",
    mode: "dark",
    premium: true,
    css: {
      "--primary": "220 90% 56%",
      "--primary-foreground": "0 0% 100%",
      "--accent": "0 0% 100%",
      "--accent-foreground": "0 0% 10%",
      "--background": "225 28% 6%",
      "--hud-grid-color": "rgba(108,211,255,0.18)",
    },
    wallpaper: "division-agent",
    accentGradient: gradients.data,
    badges: ["Premium"],
    tags: ["compliance", "security"],
  },
  {
    id: "aviation",
    name: "Aviation Beacon",
    description: "Azure and violet accents for runway and airside scheduling.",
    category: "premium",
    mode: "dark",
    premium: true,
    css: {
      "--primary": "197 100% 50%",
      "--primary-foreground": "0 0% 10%",
      "--accent": "258 90% 64%",
      "--accent-foreground": "0 0% 10%",
      "--background": "234 26% 10%",
    },
    wallpaper: "night-ops-grid",
    accentGradient: gradients.data,
    badges: ["Premium"],
    tags: ["aviation", "runway"],
  },
  {
    id: "landscaping",
    name: "Campus Grounds",
    description: "Verdant palette for campus planning and grounds dashboards.",
    category: "premium",
    mode: "dark",
    premium: true,
    css: {
      "--primary": "133 70% 41%",
      "--primary-foreground": "0 0% 98%",
      "--accent": "43 93% 55%",
      "--accent-foreground": "0 0% 10%",
      "--background": "105 18% 8%",
    },
    wallpaper: "revival",
    badges: ["Premium"],
    tags: ["grounds", "campus"],
  },
];
