name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run lint
      - run: npm run typecheck
      - run: npm run build
      - run: npm run audit
      - run: npm run test
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - run: npm run e2e

  codeql:
    permissions:
      security-events: write
    uses: github/codeql-action/.github/workflows/codeql.yml@v3
